# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 490a5f7fc411d066de1327713b80606bc51eba7dcd2a89e8851e40e4a9710bdc4dbad5e25239824feb0a0c52eabdc17292d82427b59b2ee92585dd4f0cb3c160

test:
  secret_key_base: 030dd815b3b172b0163b80e1deaa3808259ea50ac0c2ab8728fa96b66284aae478650c05033fe2d910b0a71e9b5b882d08ff7ff2c6bff136404fde61eee14d03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
